server:
  port: 8777

spring:
  application:
    name: rabbitmq-receive
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: spring_boot
      uri: mongodb://127.0.0.1:27017